"""real estate base table

Revision ID: 274cba72e323
Revises: 7959a38f79f4
Create Date: 2019-10-09 14:31:47.874415

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '274cba72e323'
down_revision = '7959a38f79f4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('developer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('dt', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('housing_complex',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('developer_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('name_eng', sa.String(length=128), nullable=True),
    sa.Column('region', sa.String(length=128), nullable=True),
    sa.Column('region_city', sa.String(length=128), nullable=True),
    sa.Column('district_direction', sa.String(length=64), nullable=True),
    sa.Column('atd', sa.String(length=128), nullable=True),
    sa.Column('zone', sa.String(length=128), nullable=True),
    sa.Column('lat', sa.Float(precision=8, asdecimal=5), nullable=True),
    sa.Column('lng', sa.Float(precision=8, asdecimal=5), nullable=True),
    sa.Column('dt', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['developer_id'], ['developer.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('house',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('developer_id', sa.Integer(), nullable=True),
    sa.Column('housing_complex_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('name_corpus', sa.String(length=64), nullable=True),
    sa.Column('address', sa.String(length=256), nullable=True),
    sa.Column('house_type', sa.String(length=64), nullable=True),
    sa.Column('house_class', sa.String(length=128), nullable=True),
    sa.Column('decoration', sa.String(length=64), nullable=True),
    sa.Column('agreement', sa.String(length=8), nullable=True),
    sa.Column('date_complete', sa.String(length=16), nullable=True),
    sa.Column('stage', sa.String(length=16), nullable=True),
    sa.Column('dt', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['developer_id'], ['developer.id'], ),
    sa.ForeignKeyConstraint(['housing_complex_id'], ['housing_complex.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('object',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('developer_id', sa.Integer(), nullable=True),
    sa.Column('housing_complex_id', sa.Integer(), nullable=True),
    sa.Column('house_id', sa.Integer(), nullable=True),
    sa.Column('room', sa.Integer(), nullable=True),
    sa.Column('square', sa.Float(), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('price_meter', sa.Float(), nullable=True),
    sa.Column('floor', sa.Integer(), nullable=True),
    sa.Column('floor_number', sa.Integer(), nullable=True),
    sa.Column('house_number', sa.Integer(), nullable=True),
    sa.Column('section_number', sa.Integer(), nullable=True),
    sa.Column('type_studio', sa.String(length=16), nullable=True),
    sa.Column('type', sa.String(length=32), nullable=True),
    sa.Column('decoration', sa.String(length=16), nullable=True),
    sa.Column('price_discont', sa.Float(), nullable=True),
    sa.Column('source', sa.String(length=128), nullable=True),
    sa.Column('dt', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['developer_id'], ['developer.id'], ),
    sa.ForeignKeyConstraint(['house_id'], ['house.id'], ),
    sa.ForeignKeyConstraint(['housing_complex_id'], ['housing_complex.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('object')
    op.drop_table('house')
    op.drop_table('housing_complex')
    op.drop_table('developer')
    # ### end Alembic commands ###
