"""district_directions and atd

Revision ID: 6531757181e8
Revises: e76e8bfb97b5
Create Date: 2019-10-15 17:25:45.643451

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6531757181e8'
down_revision = 'e76e8bfb97b5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('atd',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('dt', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('district_direction',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('dt', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('housing_complex', sa.Column('atd_id', sa.Integer(), nullable=True))
    op.add_column('housing_complex', sa.Column('district_direction_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('housing_complex', 'district_direction_id')
    op.drop_column('housing_complex', 'atd_id')
    op.drop_table('district_direction')
    op.drop_table('atd')
    # ### end Alembic commands ###
