"""add house.date_complete_id

Revision ID: 96e5a0330bcb
Revises: 210cf617e787
Create Date: 2019-10-23 20:30:11.954748

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '96e5a0330bcb'
down_revision = '210cf617e787'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('house', sa.Column('date_complete_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('house', 'date_complete_id')
    # ### end Alembic commands ###
