"""objecthouse table

Revision ID: e40eb2bb2129
Revises: 274cba72e323
Create Date: 2019-10-14 17:07:58.106750

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e40eb2bb2129'
down_revision = '274cba72e323'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('object_house',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('developer_id', sa.Integer(), nullable=True),
    sa.Column('housing_complex_id', sa.Integer(), nullable=True),
    sa.Column('house_id', sa.Integer(), nullable=True),
    sa.Column('room', sa.Integer(), nullable=True),
    sa.Column('square', sa.Float(), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('price_meter', sa.Float(), nullable=True),
    sa.Column('floor', sa.Integer(), nullable=True),
    sa.Column('floor_number', sa.Integer(), nullable=True),
    sa.Column('house_number', sa.Integer(), nullable=True),
    sa.Column('section_number', sa.Integer(), nullable=True),
    sa.Column('type_studio', sa.String(length=16), nullable=True),
    sa.Column('type', sa.String(length=32), nullable=True),
    sa.Column('decoration', sa.String(length=16), nullable=True),
    sa.Column('price_discont', sa.Float(), nullable=True),
    sa.Column('source', sa.String(length=128), nullable=True),
    sa.Column('house_name', sa.String(length=128), nullable=True),
    sa.ForeignKeyConstraint(['developer_id'], ['developer.id'], ),
    sa.ForeignKeyConstraint(['house_id'], ['house.id'], ),
    sa.ForeignKeyConstraint(['housing_complex_id'], ['housing_complex.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('object_house')
    # ### end Alembic commands ###
