"""city_region table

Revision ID: e76e8bfb97b5
Revises: 6bd24081fd96
Create Date: 2019-10-15 15:45:14.048191

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e76e8bfb97b5'
down_revision = '6bd24081fd96'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('region_city',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('dt', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('housing_complex', sa.Column('region_city_id', sa.Integer(), nullable=True))
    # op.create_foreign_key(None, 'housing_complex', 'region_city', ['region_city_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_constraint(None, 'housing_complex', type_='foreignkey')
    # op.drop_column('housing_complex', 'region_city_id')
    op.drop_table('region_city')
    # ### end Alembic commands ###
